(1-5)中級 確認用パスワード
CharlesNguyen-organization/ex-emp-management-bugfix pull request #30
Opened 2023-06-09 07:30 UTC by quangtung98

確認用パスワード欄をつけました。レビューをお願いします

2023-06-09 08:10 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-06-09 08:10 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("passwordCheck", "上のパスワードと一致しません");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2023-06-11 06:06 UTC, quangtung98 commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("passwordCheck", "上のパスワードと一致しません");
エラーメッセージの登録はBindingResultのrejectValue()メソッドに書き換えました。
再レビューをお願いします

2023-06-12 00:39 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-06-12 00:39 UTC, merged